
[project]
name = "simple-backup-tool"
version = "1.0b2"
description = "A small CLI tool for making backups to your Google Drive cloud"
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
authors = [
    { name = "imKokoT" }
]

dependencies = [
  "colorama",
  "colorlog",
  "ruamel.yaml",
  "pathspec",
  "google-api-python-client", 
  "google-auth-httplib2",
  "google-auth-oauthlib",
  "cryptography"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
sbt = "main:main"
